# Generated by Django 5.1.1 on 2024-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenizeinformation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
