# Generated by Django 5.1.1 on 2024-09-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='philbizz_api.accounts'),
            preserve_default=False,
        ),
    ]
