# Generated by Django 5.1.1 on 2024-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0002_tokenizeinformation_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accessgroup',
            name='access_level',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50),
        ),
    ]
