# Generated by Django 5.1.1 on 2024-09-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0003_menu_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_by',
        ),
    ]
