# Generated by Django 5.1.1 on 2024-09-25 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0004_accounts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pb_blacklisted_tokens',
            },
        ),
    ]
