# Generated by Django 5.1.1 on 2024-11-05 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0008_navbarcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='philbizz_api.navbarcontent'),
        ),
    ]
