# Generated by Django 5.1.1 on 2024-11-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0009_business_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarcontent',
            name='icons',
            field=models.TextField(null=True),
        ),
    ]
