# Generated by Django 5.1.1 on 2024-11-19 02:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('philbizz_api', '0013_personinvolve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
